install.packages("bigmemory", repos="http://cran.us.r-project.org")
install.packages("foreach", repos="http://cran.us.r-project.org")
install.packages("iterators", repos="http://cran.us.r-project.org")
install.packages("doMC", repos="http://cran.us.r-project.org")
install.packages("doSNOW", repos="http://cran.us.r-project.org")
install.packages("itertools", repos="http://cran.us.r-project.org")
install.packages("rmarkdown", repos='https://cran.rstudio.com/')
install.packages("shiny", repos='https://cran.rstudio.com/')
